sonar.projectKey=mahoyos_Numerical-Analysis
sonar.organization=mahoyos

# Sources
sonar.sources=backend,frontend/src
sonar.tests=backend/tests,frontend/cypress/e2e
sonar.exclusions=**/node_modules/**,frontend/dist/**,backend/__init__.py,**/.github/**,backend/.coverage
sonar.test.inclusions=backend/tests/**/*.py,frontend/cypress/e2e/**/*.ts

# Backend Configurations (Python)
sonar.python.version=3.12
sonar.python.pylint.reportPaths=pylint-report.txt
sonar.python.flake8.reportPaths=flake8-report.txt
sonar.python.coverage.reportPaths=coverage.xml

# Frontend Configurations (JavaScript / TypeScript)
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

# Quality Gate Settings
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300