sonar.projectKey=mahoyos_Numerical-Analysis
sonar.organization=mahoyos

# Sources
sonar.sources=backend,frontend/src
sonar.exclusions=**/node_modules/**,frontend/dist/**,**/tests/**,backend/__init__.py,**/.github/**,cypress/**

# Backend Configurations (Python)
sonar.python.version=3.12
sonar.python.pylint.reportPaths=pylint-report.txt
sonar.python.flake8.reportPaths=flake8-report.txt
sonar.python.coverage.reportPaths=coverage.xml

# Frontend Configurations (JavaScript / TypeScript)
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

# Quality Gate Settings
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300